### ISSUE TITLE
a mistake?

### ISSUE THREAD

**Issue by lyuchuny3** [da-steve101/googlenet#1]
Hi，
I've see your implementation for googlenet_v1, I think there may be a little mistake as following:

            with tf.variable_scope("inception_3a"):
                end_points['inception_3a'] = get_inception_layer( end_points['pool1'], 64, 96, 128, 16, 32, 32 )

            with tf.variable_scope("inception_3b"):
                end_points['inception_3b'] = get_inception_layer( end_points['pool1'], 128, 128, 192, 32, 96, 64 )

the second part should be replace 'pool1' with 'inception_3a'：
            with tf.variable_scope("inception_3b"):
                end_points['inception_3b'] = get_inception_layer( end_points['inception_3a'], 128, 128, 192, 32, 96, 64 )

**Comment by da-steve101** [comment]
yeah it is :) I kinda ditched this and just used the inception_v1 ( essentially the same network ) in tensorflow/models ( i didn't realize this before )
